### ISSUE TITLE
Can we get Proper Nouns for persian?

### ISSUE THREAD

**Issue by Rohit8y** [rasoolims/POSTagger#1]
Hi,
I am looking forward to extract Proper Noun or NNP or PROPERN from Persian text.
But i haven't found any library in java and Python yet which can give me expected results.
And what corpus have you used to train your model?
I hope you can help me with the same.

**Comment by rasoolims** [comment]
I think the Bijankhan corpus has information about proper nouns but I am not sure. I am not aware of any library that gives such information. Maybe it is worth looking at the Hazm library:
https://github.com/sobhe/hazm
